### ISSUE TITLE
[2.2.3_구조적 서브타이핑] Q.  44페이지 예제 관련 퀴즈들

### ISSUE THREAD

**Issue by zzznly** [ogqcorp/woowahan-ts-study#6]
```typescript
interface Pet { name: string; }
interface Cat { name: string; age: number; }
let pet: Pet;
let cat: Cat = { name: "Zag", age: 2 };
pet = cat;
```
<br/>

## 문제 (난이도 하)
**1. 왜 pet = cat; 할당이 가능한가요?**

A) Cat과 Pet은 상속 관계에 있기 때문이다.
B) Cat과 Pet의 구조가 부분적으로 같기 때문이다.
C) Cat 타입은 Pet 타입을 확장하기 때문이다.
D) 타입스크립트는 객체를 이름이 아닌 구조로 비교하기 때문이다.

<br/>

**2. cat이 pet에 할당될 때, Cat의 age 속성은 어떻게 처리되나요?**

A) age 속성도 할당되며 접근 가능해진다.
B) age 속성은 무시되고 Pet 타입으로만 동작한다.
C) 컴파일 오류가 발생한다.
D) age 속성은 할당되지만 pet에서만 접근할 수 없다.

<br/>

**3. 다음 중 Cat 타입을 Pet 타입에 할당할 수 있는 이유와 관련된 타입스크립트 개념은 무엇인가요?**

A) 동적 타이핑
B) 구조적 서브타이핑
C) 명시적 타입 변환
D) 타입 좁히기

<br/>

## 문제 (난이도 중상)

**1. 구조적 서브타이핑과 관련한 다음 설명 중 알맞은 것은?**

A) 모든 타입스크립트 인터페이스는 명시적으로 다른 인터페이스를 확장해야만 다른 타입에 할당 가능하다.
B) 인터페이스가 비록 추가적인 속성을 가지고 있더라도, 필요한 최소한의 속성을 충족시키면 다른 인터페이스 타입에 할당할 수 있다.
C) 한 타입을 다른 타입에 할당하기 위해서는 그 타입들이 반드시 같은 이름을 가져야 한다.
D) 구조적 서브타이핑은 자바스크립트의 프로토타입 상속과 동일하게 작동한다.

<br/>

**2. pet = cat; 할당이 성공적으로 이루어진 후, 다음 코드에서 컴파일 오류가 발생하는 이유는?**

```typescript
console.log(pet.age);
```

A) Pet 인터페이스에는 age 속성이 정의되어 있지 않기 때문이다.
B) pet 변수가 Cat 타입의 객체를 참조하지만, 타입 선언은 Pet으로 되어 있기 때문이다.
C) age 속성은 Cat 인터페이스의 전용 속성이므로 Pet 타입에서는 접근할 수 없다.

<br/>

**3. Pet과 Cat 인터페이스가 구조적으로 호환되는 이유에 대해 깊이 있게 설명하세요. 추가적으로, 이러한 호환성이 프로그램에 어떤 영향을 미칠 수 있는지 논의하세요.**

<br/>

**4. 구조적 서브타이핑이 타입 안전성에 미치는 영향을 고려할 때, 어떤 상황에서 개발자가 이러한 타입의 할당을 조심해야 할까요?**

**Comment by nom-juhwan** [comment]
하)
1. B
2. B
3. B

중)
1. B
2. A

**Comment by zzznly** [comment]
1. B
타입스크립트는 구조적 타이핑을 사용하여, 할당받는 타입이 요구하는 속성을 충족하는 한 다른 타입을 할당할 수 있습니다. 이름이나 상속 관계는 중요하지 않습니다.
